name: Python application and Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Ruff Check
        run: poetry run ruff check .

      - name: Run Ruff Format Check
        run: poetry run ruff format --check .

      - name: Run Static Type Check (Mypy)
        run: poetry run mypy src

      - name: Run tests
        env:
          PYTHONPATH: ./src
          GEMINI_API_KEY: "fake_key"
          TELEGRAM_BOT_TOKEN: "fake_token"
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          poetry run pytest --cov-report=html

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: htmlcov/
